plex:
  url: "http://localhost:32400"                     # The URL of your Plex Media Server
  token: "YOUR_PLEX_TOKEN"                     # Your Plex API authentication token
  music_library: "Music"                            # The name of your Plex music library


playlist:
  exclude_played_days: 4                            # Ignore tracks played in the last X days to avoid repeats
  history_lookback_days: 30                         # How many days of listening history to analyze for playlist generation
  max_tracks: 50                                    # The maximum number of tracks allowed in a single playlist
  sonic_similar_limit: 8                            # Number of sonically similar tracks to fetch for each track during sorting
  
  historical_ratio: 0.3                             # The max % of tracks sourced from listening history for each playlist
  sonic_similarity_limit: 50                        # Number of tracks to check for sonic similarity per reference track (higher number is more accurate but takes longer; shouldn't be higher than max tracks)
  sonic_similarity_distance: 1.0                    # Maximum similarity distance for sonic matching (lower = stricter matching)


directories:
  cover_images: "assets/covers/flat"    # Path where cover images for playlists are stored
  fonts: "assets/fonts"          # Path to font files used for text overlays


fonts:
  main: "Circular/Circular-Bold.ttf"                # Primary font used for playlist covers
  meloday: "Circular/Circular-Bold.ttf"             # Specific font for "Meloday" branding on covers


time_periods:
  Dawn: 
    hours: [3, 4, 5]   
    cover: "dawn_blank.webp"
  "Early Morning": 
    hours: [6, 7, 8]
    cover: "early-morning_blank.webp"
  Morning: 
    hours: [9, 10, 11]
    cover: "morning_blank.webp"
  Afternoon: 
    hours: [12, 13, 14, 15]
    cover: "afternoon_blank.webp"
  Evening: 
    hours: [16, 17, 18]
    cover: "evening_blank.webp"
  Night: 
    hours: [19, 20, 21]
    cover: "night_blank.webp"
  "Late Night": 
    hours: [22, 23, 0, 1, 2]           
    cover: "late-night_blank.webp"

files:
  mood_map: "assets/moodmap.json"             

period_phrases:
  Dawn: "at dawn"
  "Early Morning": "in the early morning"
  Morning: "in the morning"
  Afternoon: "during the afternoon"
  Evening: "in the evening"
  Night: "at night"
  "Late Night": "late at night"
